# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci --only=production", "cd frontend && npm ci"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[phases.start]
cmd = "npm start"
